name: AFK Journey Coupon Auto Crawler

on:
  schedule:
    - cron: '0 */6 * * *' # 6시간마다 자동 실행
  workflow_dispatch: # 수동 실행 버튼

# 깃허브 봇에게 저장소 파일 쓰기 권한 부여
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v4

      - name: 파이썬 설정
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 필수 라이브러리 설치
        run: |
          pip install requests beautifulsoup4

      - name: 크롤러 실행
        run: python crawler.py

      - name: 결과 파일 저장 및 깃허브 푸시
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add afk_journey.json
          git commit -m "Auto update afk_journey.json" || exit 0
          git push
